version: "3.9"

networks:
  hotelaria-network:
    driver: bridge

services:
  hotelaria-db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - hotelaria-network
